service: mathematical-web-service

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: '20201221'

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get

configValidationMode: error
